# Generated by Django 5.1.6 on 2025-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='edit_link',
        ),
        migrations.AddField(
            model_name='character',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
