# Generated by Django 5.1.6 on 2025-03-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
