# Generated by Django 5.1.6 on 2025-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=1, verbose_name='ХАР'),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=1, verbose_name='ТЕЛ'),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=1, verbose_name='ЛОВ'),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=1, verbose_name='ИНТ'),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.TextField(blank=True, null=True, verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Раса'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=1, verbose_name='СИЛ'),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=1, verbose_name='МДР'),
        ),
    ]
